### PR TITLE
Fix ttf format

### PR DESCRIPTION
**Pull request by burdulixda**
Hello again.

I fixed the SCSS code according to your suggestion and also added some test cases. I also wanna point out that I'm using this code in production now and seems to be working perfectly fine. WOFF fonts get .woff extension and 'woff' format, while TTF fonts get .ttf extension and 'truetype' format.

### CODE REVIEW

**Comment by Dan503** [comment]
I've fixed up the tests. I was after new tests rather than modified old ones though the generator doesn't really lend itself well to doing multiple tests so I just added ttf to the existing test on that one.

>  I also wanna point out that I'm using this code in production now and seems to be working perfectly fine

The issue I saw was with how the code was handling the case of `$types: 'ttf' 'woff'`. As in multiple file types in the one rule.

I'm guessing you are only loading the one ttf file type in production which is why it would have worked for you.

**Comment by Dan503** [comment]
Thanks for the fix. I've published it to npm as v1.1.2 now 🙂

**Comment by Dan503** [comment]
For reference, the original PR https://github.com/Dan503/font-face-generator/pull/5

@burdulixda I've also added a [contributing](https://github.com/Dan503/font-face-generator#contributing) section in this release to `readme.md` now. Thanks for the suggestion.

**Comment by burdulixda** [comment]
Thanks for this awesome mixin, cheers.

**Pull request merged**
